name: Write Release Notes

on:
    release:
        types: [published]

jobs:
    release-notes:
        uses: AlbertPuwadol/pr-template/.github/workflows/release-notes.yml@master
        with:
            release_tag: ${{ github.ref_name }}
            repository_name: ${{ github.repository }}
        secrets: inherit
